import{a as q,S as E,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const A="52532221-25d3743a49e2ba4d3d583822e",$="https://pixabay.com/api/",h=15,B=q.create({baseURL:$,params:{key:A,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h}});async function y(t,r=1){const o=(t??"").trim(),{data:s}=await B.get("",{params:{q:o,page:r}});return s}const m=document.querySelector("#gallery"),p=document.querySelector("#loader"),c=document.querySelector("#load-more"),M=new E(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function b(t=[]){if(!t.length)return;const r=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:a,views:l,comments:v,downloads:P})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${s}">
    <img class="gallery-image" src="${o}" alt="${H(e)}" loading="lazy" />
  </a>
  <ul class="meta">
    <li><span>Likes</span><b>${a}</b></li>
    <li><span>Views</span><b>${l}</b></li>
    <li><span>Comments</span><b>${v}</b></li>
    <li><span>Downloads</span><b>${P}</b></li>
  </ul>
</li>`).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function O(){m.innerHTML=""}function w(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}function S(){c&&(c.hidden=!1)}function u(){c&&(c.hidden=!0)}function H(t=""){return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}const x=document.querySelector("#search-form"),d=document.querySelector("#load-more"),R=document.querySelector("#gallery");let g="",i=1,f=0;n.settings({position:"topRight",timeout:3e3,closeOnClick:!0});x.addEventListener("submit",_);d&&d.addEventListener("click",C);async function _(t){t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term"});return}g=r,i=1,f=0,O(),u(),w();try{const o=await y(g,i);if(f=o.totalHits??0,!Array.isArray(o.hits)||o.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}b(o.hits),o.hits.length+(i-1)*h<f?S():(u(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Please try again later."})}finally{L()}}async function C(){d.disabled=!0,w();try{i+=1;const t=await y(g,i);if(!Array.isArray(t.hits)||t.hits.length===0){u(),n.info({message:"We're sorry, but you've reached the end of search results."});return}b(t.hits);const r=R.querySelector(".gallery-item");if(r){const{height:s}=r.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}i*h>=(t.totalHits??0)?(u(),n.info({message:"We're sorry, but you've reached the end of search results."})):S()}catch{n.error({message:"Something went wrong. Please try again later."})}finally{L(),d.disabled=!1}}
//# sourceMappingURL=index.js.map
