import{a as q,S as A,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const E="52532221-25d3743a49e2ba4d3d583822e",B="https://pixabay.com/api/",g=15,H=q.create({baseURL:B,params:{key:E,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g}});async function p(e,r=1){const o=(e??"").trim(),{data:s}=await H.get("",{params:{q:o,page:r}});return s}const m=document.querySelector("#gallery"),i=document.querySelector("#loader"),h=document.querySelector("#load-more"),M=new A(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function b(e=[]){if(!Array.isArray(e)||e.length===0)return;const r=e.map(({webformatURL:o,largeImageURL:s,tags:t,likes:n,views:u,comments:v,downloads:P})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${s}">
    <img class="gallery-image" src="${o}" alt="${x(t)}" loading="lazy" />
  </a>
  <ul class="meta">
    <li><span>Likes</span><b>${n}</b></li>
    <li><span>Views</span><b>${u}</b></li>
    <li><span>Comments</span><b>${v}</b></li>
    <li><span>Downloads</span><b>${P}</b></li>
  </ul>
</li>`).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){m.innerHTML=""}function w(){i&&(i.classList.add("is-visible"),i.hidden=!1)}function L(){i&&(i.classList.remove("is-visible"),i.hidden=!0)}function S(){h&&(h.hidden=!1)}function c(){h&&(h.hidden=!0)}function O(){const e=m.querySelector(".gallery-item");if(!e)return 0;const{height:r}=e.getBoundingClientRect();return r}function x(e=""){return String(e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}const R=document.querySelector("#search-form"),d=document.querySelector("#load-more");document.querySelector("#gallery");let y="",l=1,f=0;a.settings({position:"topRight",timeout:3e3,closeOnClick:!0});typeof c=="function"&&c();R.addEventListener("submit",_);d&&d.addEventListener("click",C);async function _(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(!r){a.warning({message:"Please enter a search term"});return}y=r,l=1,f=0,$(),c(),w();try{const o=await p(y,l);if(f=o.totalHits??0,!Array.isArray(o.hits)||o.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}b(o.hits),o.hits.length+(l-1)*g<f?S():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Something went wrong. Please try again later."})}finally{L()}}async function C(){if(y&&d){d.disabled=!0,w();try{l+=1;const e=await p(y,l);if(!Array.isArray(e.hits)||e.hits.length===0){c(),a.info({message:"We're sorry, but you've reached the end of search results."});return}b(e.hits);const r=O();r>0&&window.scrollBy({top:r*2,behavior:"smooth"}),l*g>=(e.totalHits??f)?(c(),a.info({message:"We're sorry, but you've reached the end of search results."})):S()}catch{a.error({message:"Something went wrong. Please try again later."})}finally{L(),d.disabled=!1}}}
//# sourceMappingURL=index.js.map
